// ============================================================================
// packages/cli/adapters/openapi.ts — OpenAPI 3.0/3.1 → .flow project
// ============================================================================
// A compiler FRONT-END, not a shortcut around the compiler.
//
// This emits .flow source files, never manifest.json. That is deliberate and
// load-bearing: the generated files then go through the ordinary `axl compile`,
// so the existing validator still gates them (AXL322 "every action needs a
// PERMISSION", unknown type references, duplicate names, and everything else).
// Emitting a manifest directly would route around the single source of truth
// that the whole adapter model exists to preserve.
//
// ── The security default ────────────────────────────────────────────────────
//
// Every generated action is AUTH. Never PUBLIC, under any inferred condition,
// and never CONFIRM.
//
// An OpenAPI spec has no concept of AXL's PERMISSION or CONFIRM semantics.
// `security: []` on an operation means "this operation overrides the global
// requirement", which is a statement about the spec author's HTTP auth scheme
// -- not a statement that the endpoint is safe to expose to an unauthenticated
// caller through AXL. Silence in a source spec is not evidence of intent, and
// a spec's own auth documentation is routinely incomplete or stale. Guessing
// permissive is the exact failure mode that produces a security hole nobody
// reviews, so the importer does not guess at all: it defaults closed and marks
// every entry for human review.
//
// CONFIRM is not inferred either. Whether an action is destructive enough to
// warrant an OTP gate is a business-risk judgement about a specific product --
// DELETE /sessions (log out) and DELETE /accounts (irreversible) are the same
// HTTP verb. Generating a gate from the verb would be guessing, and generating
// none while looking thorough is worse.
// ============================================================================

import { validate, dereference } from "@readme/openapi-parser";

export interface AdaptResult {
  files: Record<string, string>;
  stats: {
    actions: number;
    entities: number;
    todoEntities: number;
    operationsWithoutOperationId: number;
    unmappableFields: number;
  };
  notes: string[];
}

/** AXL primitives, for deciding whether a generated type reference resolves. */
const AXL_PRIMITIVES = new Set(["String", "Number", "Float", "Boolean", "Null"]);

const REVIEW_BANNER = [
  "-- ============================================================================",
  "-- GENERATED BY `axl adapt openapi` — REVIEW BEFORE SERVING",
  "-- ============================================================================",
  "-- Every PERMISSION below was defaulted to AUTH. None of it was inferred from",
  "-- the source spec, because an OpenAPI document carries no AXL permission",
  "-- semantics and guessing permissive is unsafe.",
  "--",
  "-- You must review every line. For each action decide:",
  "--   * AUTH stays          — the caller must have a session (the safe default)",
  "--   * change to PUBLIC    — ONLY if genuinely safe with no session at all",
  "--   * ROLE <role>         — restricted to a role (needs --trust-identity-headers)",
  "--   * OWNER <input>       — the caller may only act on their own id",
  "--   * add CONFIRM : OTP   — if the action is destructive or otherwise needs a",
  "--                           human to approve it before it runs",
  "--",
  "-- NO CONFIRM entries were generated. That is a business-risk judgement about",
  "-- your product, not something an HTTP method can imply: DELETE /sessions and",
  "-- DELETE /accounts are the same verb with very different consequences.",
  "-- ============================================================================",
  "",
];

// ---------------------------------------------------------------------------
// Naming
// ---------------------------------------------------------------------------

/**
 * The lexer accepts letters, digits, `_` and `-` in identifiers. Anything else in an
 * operationId or schema name has to go, or the generated file will not parse.
 */
function sanitizeIdent(raw: string): string {
  const cleaned = String(raw)
    .replace(/[^A-Za-z0-9_-]+/g, "_")
    .replace(/_+/g, "_")
    .replace(/^_+|_+$/g, "");
  // An identifier must not start with a digit -- the lexer would read a number.
  return /^[0-9]/.test(cleaned) ? `_${cleaned}` : cleaned;
}

function toSnake(raw: string): string {
  return sanitizeIdent(
    String(raw)
      .replace(/([a-z0-9])([A-Z])/g, "$1_$2")
      .replace(/[-\s]+/g, "_")
      .toLowerCase()
  );
}

function toPascal(raw: string): string {
  const parts = String(raw).split(/[^A-Za-z0-9]+/).filter(Boolean);
  const joined = parts.map(p => p.charAt(0).toUpperCase() + p.slice(1)).join("");
  return sanitizeIdent(joined || "Unnamed");
}

/**
 * Fallback action name when an operation has no operationId. Derived from method and
 * path so it is stable across runs: `GET /users/{id}/posts` -> `get_users_by_id_posts`.
 * Which strategy was used is recorded in a comment on the action itself, because a
 * derived name is a thing the developer may well want to rename.
 */
function deriveActionName(method: string, routePath: string): string {
  const segments = String(routePath)
    .split("/")
    .filter(Boolean)
    .map(seg => {
      const param = seg.match(/^\{(.+)\}$/);
      return param ? `by_${toSnake(param[1]!)}` : toSnake(seg);
    })
    .filter(Boolean);
  return toSnake([method.toLowerCase(), ...segments].join("_")) || toSnake(method);
}

// ---------------------------------------------------------------------------
// Type mapping
// ---------------------------------------------------------------------------

interface MappedType {
  /** The AXL type expression, e.g. "String", "List<Order>". */
  type: string;
  /** Set when the source schema could not be represented faithfully. */
  problem?: string;
}

/**
 * Maps one OpenAPI schema to an AXL type.
 *
 * Anything AXL cannot represent returns a `problem` rather than a quiet approximation.
 * Callers surface that as a TODO comment in the generated source: a developer who can
 * see "this was a oneOf and became String" can fix it, whereas a silent String is a gap
 * that only shows up much later as a runtime shape mismatch.
 */
function mapType(schema: any, entityNames: Set<string>, refName?: string): MappedType {
  if (!schema || typeof schema !== "object") {
    return { type: "String", problem: "no schema given; defaulted to String" };
  }

  // A named component we already emitted as an ENTITY.
  if (refName && entityNames.has(refName)) return { type: refName };

  if (Array.isArray(schema.oneOf) || Array.isArray(schema.anyOf)) {
    const kind = schema.oneOf ? "oneOf" : "anyOf";
    return {
      type: "String",
      problem: `source schema used ${kind} (polymorphism); AXL has no union type, so this became String`,
    };
  }
  if (Array.isArray(schema.allOf)) {
    return {
      type: "String",
      problem: "source schema used allOf (composition); AXL has no intersection type, so this became String",
    };
  }

  // 3.1 allows `type` to be an array, e.g. ["string","null"].
  let type = schema.type;
  let nullable = false;
  if (Array.isArray(type)) {
    const nonNull = type.filter((t: string) => t !== "null");
    nullable = type.length !== nonNull.length;
    if (nonNull.length > 1) {
      return {
        type: "String",
        problem: `source schema allowed multiple types (${type.join(", ")}); AXL has no union type, so this became String`,
      };
    }
    type = nonNull[0];
  }

  if (schema.enum && !type) type = typeof schema.enum[0] === "number" ? "number" : "string";

  switch (type) {
    case "string":
      return { type: "String" };
    case "integer":
      return { type: "Number" };
    case "number":
      return { type: "Float" };
    case "boolean":
      return { type: "Boolean" };
    case "null":
      return { type: "Null" };
    case "array": {
      const itemRef = refNameOf(schema.items);
      const inner = mapType(schema.items, entityNames, itemRef);
      return {
        type: `List<${inner.type}>`,
        problem: inner.problem ? `list element: ${inner.problem}` : undefined,
      };
    }
    case "object": {
      if (refName && entityNames.has(refName)) return { type: refName };
      return {
        type: "String",
        problem: "source schema was an inline/free-form object; AXL entities are named, so this became String",
      };
    }
    default:
      if (nullable) return { type: "String", problem: "source schema was nullable-only; defaulted to String" };
      return {
        type: "String",
        problem: `source schema had no recognisable type${type ? ` ("${type}")` : ""}; defaulted to String`,
      };
  }
}

/** Recovers the component name a $ref pointed at, after dereferencing preserved it. */
function refNameOf(schema: any): string | undefined {
  if (!schema || typeof schema !== "object") return undefined;
  const ref = schema.$ref || schema["x-axl-ref-name"];
  if (typeof ref !== "string") return undefined;
  const m = ref.match(/#\/components\/schemas\/(.+)$/);
  return m ? toPascal(m[1]!) : undefined;
}

// ---------------------------------------------------------------------------
// Emitters
// ---------------------------------------------------------------------------

function quote(text: string): string {
  // The lexer's string literal has no escape handling, so a quote or newline inside
  // DESC would terminate it early and derail the parse.
  return `"${String(text).replace(/[\r\n]+/g, " ").replace(/"/g, "'").trim()}"`;
}

function firstLine(text: unknown): string {
  if (typeof text !== "string") return "";
  return text.replace(/[\r\n]+/g, " ").trim();
}

function buildAppFlow(api: any, notes: string[]): string {
  const info = api.info || {};
  const appName = toPascal(info.title || "ImportedApi");
  const lines: string[] = ["-- app.flow", "-- Generated by `axl adapt openapi`.", ""];

  lines.push(`APP ${appName}`, "");
  if (info.title) lines.push(`NAME ${quote(info.title)}`, "");

  // AXL wants a semver-shaped version; an OpenAPI `info.version` is free-form and
  // very often something like "2024-01-01" or "v3".
  const rawVersion = String(info.version ?? "").trim();
  if (/^\d+\.\d+\.\d+$/.test(rawVersion)) {
    lines.push(`VERSION ${rawVersion}`, "");
  } else {
    lines.push(
      `-- TODO: the source spec's info.version was ${rawVersion ? `"${rawVersion}"` : "absent"},`,
      "-- which is not the MAJOR.MINOR.PATCH form AXL expects. Defaulted to 1.0.0.",
      "VERSION 1.0.0",
      ""
    );
    if (rawVersion) notes.push(`info.version "${rawVersion}" was not semver; wrote 1.0.0`);
  }

  if (info.description) lines.push(`DESCRIPTION ${quote(firstLine(info.description))}`, "");

  const server = Array.isArray(api.servers) ? api.servers[0] : undefined;
  const url = server && typeof server.url === "string" ? server.url.trim() : "";
  // A relative server URL ("/api/v1") is legal OpenAPI but useless as a BASE_URL: the
  // engine concatenates it with the endpoint path and hands the result to fetch().
  if (url && /^https?:\/\//i.test(url)) {
    lines.push(`BASE_URL ${url}`, "");
  } else {
    lines.push(
      "-- TODO: FILL THIS IN. The source spec " +
        (url
          ? `declared a relative server URL ("${url}"), which is not usable as a BASE_URL --`
          : "declared no servers[0].url, so there is nothing to import --"),
      "-- AXL needs an absolute origin to send backend requests to.",
      url ? `BASE_URL http://localhost:3000${url}` : "BASE_URL http://localhost:3000",
      ""
    );
    notes.push(
      url
        ? `servers[0].url was relative ("${url}"); BASE_URL needs completing by hand`
        : "spec declared no servers[0].url; BASE_URL needs filling in by hand"
    );
  }

  return lines.join("\n");
}

interface EntityPlan {
  name: string;
  lines: string[];
  todo: boolean;
}

function buildSchemaFlow(api: any, entityNames: Set<string>, stats: AdaptResult["stats"]): string {
  const schemas = api.components?.schemas || {};
  const out: string[] = ["-- schema.flow", "-- Generated by `axl adapt openapi`.", ""];
  const plans: EntityPlan[] = [];

  for (const [rawName, schema] of Object.entries<any>(schemas)) {
    const name = toPascal(rawName);
    const lines: string[] = [];
    let todo = false;

    const isObject =
      schema &&
      (schema.type === "object" ||
        (Array.isArray(schema.type) && schema.type.includes("object")) ||
        (!schema.type && schema.properties));

    if (!isObject) {
      // A top-level non-object component (a bare enum, a union, a scalar alias) has no
      // ENTITY equivalent. Emitted as a marked stub rather than skipped, so the gap is
      // visible in the file the developer reads.
      const why = Array.isArray(schema?.oneOf)
        ? "a oneOf union"
        : Array.isArray(schema?.anyOf)
        ? "an anyOf union"
        : Array.isArray(schema?.allOf)
        ? "an allOf composition"
        : schema?.enum
        ? "a bare enum"
        : `a non-object schema (type: ${JSON.stringify(schema?.type) ?? "none"})`;
      lines.push(
        `-- TODO: "${rawName}" in the source spec is ${why}, which has no ENTITY`,
        "-- equivalent in AXL. Nothing was auto-converted. Define the fields you",
        "-- actually need by hand, or delete this block if the type is unused.",
        `ENTITY ${name}`,
        "",
        "-- TODO: no fields could be derived. An entity with no fields will not compile;",
        "-- add at least one, or remove this entity and the references to it.",
        `placeholder : String`
      );
      todo = true;
      stats.todoEntities++;
    } else {
      const props = schema.properties || {};
      const propEntries = Object.entries<any>(props);
      if (propEntries.length === 0) {
        lines.push(
          `-- TODO: "${rawName}" is an object with no declared properties in the source`,
          "-- spec (free-form). A placeholder field is emitted so this compiles; replace it.",
          `ENTITY ${name}`,
          "",
          "placeholder : String"
        );
        todo = true;
        stats.todoEntities++;
      } else {
        lines.push(`ENTITY ${name}`, "");
        for (const [propName, propSchema] of propEntries) {
          const fieldName = toSnake(propName);
          const mapped = mapType(propSchema, entityNames, refNameOf(propSchema));
          if (mapped.problem) {
            lines.push(`-- TODO: field "${propName}" — ${mapped.problem}`);
            stats.unmappableFields++;
          }
          lines.push(`${fieldName} : ${mapped.type}`);
        }
      }
    }

    plans.push({ name, lines, todo });
  }

  if (plans.length === 0) {
    out.push("-- The source spec declared no components.schemas, so there are no entities.");
    out.push("-- Actions below use primitive OUTPUT types.");
    return out.join("\n") + "\n";
  }

  for (const plan of plans) {
    out.push(...plan.lines, "");
  }
  return out.join("\n");
}

/** Collects the entity names first, so a property referencing another schema resolves. */
function collectEntityNames(api: any): Set<string> {
  const names = new Set<string>();
  for (const rawName of Object.keys(api.components?.schemas || {})) {
    names.add(toPascal(rawName));
  }
  return names;
}

const HTTP_METHODS = ["get", "post", "put", "patch", "delete"];

interface OperationPlan {
  name: string;
  derivedName: boolean;
  method: string;
  routePath: string;
  summary: string;
  inputs: { name: string; type: string; required: boolean; desc: string; problem?: string }[];
  output: string;
  outputProblem?: string;
}

function planOperations(api: any, entityNames: Set<string>, stats: AdaptResult["stats"]): OperationPlan[] {
  const plans: OperationPlan[] = [];
  const usedNames = new Map<string, number>();

  for (const [routePath, pathItem] of Object.entries<any>(api.paths || {})) {
    if (!pathItem || typeof pathItem !== "object") continue;
    const pathLevelParams = Array.isArray(pathItem.parameters) ? pathItem.parameters : [];

    for (const method of HTTP_METHODS) {
      const op = pathItem[method];
      if (!op || typeof op !== "object") continue;

      let name: string;
      let derivedName = false;
      if (typeof op.operationId === "string" && op.operationId.trim()) {
        name = toSnake(op.operationId);
      } else {
        name = deriveActionName(method, routePath);
        derivedName = true;
        stats.operationsWithoutOperationId++;
      }

      // Two operations can sanitise to the same identifier ("getUser" and "get_user").
      // A duplicate ACTION name is a compile error, so disambiguate deterministically.
      const seen = usedNames.get(name);
      if (seen !== undefined) {
        usedNames.set(name, seen + 1);
        name = `${name}_${seen + 1}`;
      } else {
        usedNames.set(name, 0);
      }

      const inputs: OperationPlan["inputs"] = [];
      const seenInputs = new Set<string>();

      for (const param of [...pathLevelParams, ...(Array.isArray(op.parameters) ? op.parameters : [])]) {
        if (!param || typeof param !== "object" || !param.name) continue;
        // header/cookie parameters are transport concerns the engine supplies itself;
        // importing them as action inputs would ask the caller for a Cookie header.
        if (param.in !== "path" && param.in !== "query") continue;
        const fieldName = toSnake(param.name);
        if (seenInputs.has(fieldName)) continue;
        seenInputs.add(fieldName);
        const mapped = mapType(param.schema, entityNames, refNameOf(param.schema));
        if (mapped.problem) stats.unmappableFields++;
        inputs.push({
          name: fieldName,
          // An action input is a scalar in the manifest's zod shape; a List or entity
          // input has no meaning as a query/path parameter.
          type: AXL_PRIMITIVES.has(mapped.type) ? mapped.type : "String",
          required: param.in === "path" ? true : Boolean(param.required),
          desc: firstLine(param.description),
          problem: mapped.problem,
        });
      }

      const bodySchema =
        op.requestBody?.content?.["application/json"]?.schema ??
        op.requestBody?.content?.[Object.keys(op.requestBody?.content || {})[0] || ""]?.schema;

      if (bodySchema && typeof bodySchema === "object") {
        const required: string[] = Array.isArray(bodySchema.required) ? bodySchema.required : [];
        const props = bodySchema.properties || {};
        for (const [propName, propSchema] of Object.entries<any>(props)) {
          const fieldName = toSnake(propName);
          if (seenInputs.has(fieldName)) continue;
          seenInputs.add(fieldName);
          const mapped = mapType(propSchema, entityNames, refNameOf(propSchema));
          if (mapped.problem) stats.unmappableFields++;
          inputs.push({
            name: fieldName,
            type: AXL_PRIMITIVES.has(mapped.type) ? mapped.type : "String",
            required: required.includes(propName),
            desc: firstLine((propSchema as any)?.description),
            problem: mapped.problem,
          });
        }
      }

      // Success response -> OUTPUT.
      const responses = op.responses || {};
      const successCode = Object.keys(responses).find(code => /^2\d\d$/.test(code)) ??
        (responses.default ? "default" : undefined);
      let output = "Null";
      let outputProblem: string | undefined;

      if (successCode) {
        const content = responses[successCode]?.content || {};
        const jsonSchema =
          content["application/json"]?.schema ??
          content[Object.keys(content)[0] || ""]?.schema;
        if (jsonSchema) {
          const mapped = mapType(jsonSchema, entityNames, refNameOf(jsonSchema));
          output = mapped.type;
          outputProblem = mapped.problem;
        } else if (Object.keys(content).length === 0) {
          // A documented 204/success with no body really is Null -- not a gap.
          output = "Null";
        } else {
          output = "String";
          outputProblem = `success response ${successCode} declared content but no schema; defaulted to String`;
        }
      } else {
        outputProblem = "no 2xx response declared in the source spec; defaulted to Null";
      }

      plans.push({
        name,
        derivedName,
        method: method.toUpperCase(),
        routePath,
        summary: firstLine(op.summary) || firstLine(op.description),
        inputs,
        output,
        outputProblem,
      });
    }
  }

  stats.actions = plans.length;
  return plans;
}

/**
 * Rewrites `{camelCase}` path placeholders to the snake_case names the INPUT block
 * declares.
 *
 * Not cosmetic. `buildUrl` resolves a placeholder by looking its name up in the action's
 * arguments, so `ENDPOINT GET /books/{bookId}` next to `book_id : String` throws
 * "Missing required path parameter: bookId" on every call. The placeholder name is
 * purely internal — only the substituted value reaches the backend — so renaming it is
 * safe and is what makes the generated action actually callable.
 */
function endpointPath(routePath: string): string {
  return routePath.replace(/\{([^}]+)\}/g, (_, name) => `{${toSnake(name)}}`);
}

function buildActionsFlow(plans: OperationPlan[]): string {
  const out: string[] = ["-- actions.flow", "-- Generated by `axl adapt openapi`.", ""];

  for (const plan of plans) {
    if (plan.derivedName) {
      out.push(
        `-- NOTE: the source operation had no operationId. This name was derived from`,
        `-- its method and path (${plan.method} ${plan.routePath}). Rename it if you prefer.`
      );
    }
    out.push(`ACTION ${plan.name}`, "");

    // DESC is required by the compiler, and AXL323 warns on a missing one. Preserve the
    // spec's own summary/description where it exists rather than emitting a stub.
    if (plan.summary) {
      out.push(`DESC ${quote(plan.summary)}`, "");
    } else {
      out.push(
        "-- TODO: the source spec documented no summary or description for this operation.",
        `DESC ${quote(`${plan.method} ${plan.routePath}`)}`,
        ""
      );
    }

    if (plan.inputs.length > 0) {
      out.push("INPUT");
      for (const input of plan.inputs) {
        if (input.problem) out.push(`-- TODO: input "${input.name}" — ${input.problem}`);
        const desc = input.desc ? ` DESC ${quote(input.desc)}` : "";
        out.push(`${input.name} : ${input.type} ${input.required ? "REQUIRED" : "OPTIONAL"}${desc}`);
      }
      out.push("");
    }

    if (plan.outputProblem) out.push(`-- TODO: OUTPUT — ${plan.outputProblem}`);
    out.push(`OUTPUT ${plan.output}`, "");
    out.push(`ENDPOINT ${plan.method} ${endpointPath(plan.routePath)}`, "");
  }

  return out.join("\n");
}

/**
 * The security-critical file. Every action gets AUTH and a review marker; nothing here
 * is inferred from the spec.
 */
function buildAuthFlow(plans: OperationPlan[]): string {
  const out: string[] = ["-- auth.flow", ...REVIEW_BANNER];

  for (const plan of plans) {
    out.push(
      "-- REVIEW REQUIRED: imported from OpenAPI with no security info. Defaulted",
      "-- to AUTH. Confirm this is correct, or change to PUBLIC if genuinely safe",
      "-- to expose without a session. Consider CONFIRM: OTP if this action is",
      "-- destructive (DELETE, or a POST/PUT that mutates significant state).",
      `--   source: ${plan.method} ${plan.routePath}`,
      `PERMISSION ${plan.name} : AUTH`,
      ""
    );
  }

  return out.join("\n");
}

// ---------------------------------------------------------------------------
// Entry point
// ---------------------------------------------------------------------------

export class OpenApiAdaptError extends Error {
  constructor(message: string, readonly details: string[] = []) {
    super(message);
  }
}

/**
 * Validates a spec and converts it to .flow sources.
 *
 * Validation happens first and hard-fails: generating half a project from a malformed
 * spec produces files whose compile errors point at the generator rather than at the
 * real problem, which sends the developer looking in the wrong place.
 */
export async function adaptOpenApi(specPath: string): Promise<AdaptResult> {
  let report;
  try {
    report = await validate(specPath);
  } catch (err) {
    throw new OpenApiAdaptError(
      `Could not read or parse the OpenAPI spec at ${specPath}`,
      [err instanceof Error ? err.message : String(err)]
    );
  }

  if (!report.valid) {
    const details = (report as any).errors?.slice(0, 8).map((e: any) =>
      firstLine(e.message) || JSON.stringify(e)
    ) ?? ["The parser reported the document as invalid but gave no details."];
    throw new OpenApiAdaptError(`${specPath} is not a valid OpenAPI document`, details);
  }

  // Dereference after validating, so $refs are resolved before mapping. Component names
  // are stashed first, because dereferencing replaces the $ref with its target and the
  // name is then unrecoverable from the schema object alone.
  const raw = await dereference(specPath);
  const api = tagRefNames(raw);

  const notes: string[] = [];
  const stats: AdaptResult["stats"] = {
    actions: 0, entities: 0, todoEntities: 0,
    operationsWithoutOperationId: 0, unmappableFields: 0,
  };

  const entityNames = collectEntityNames(api);
  stats.entities = entityNames.size;

  const schemaFlow = buildSchemaFlow(api, entityNames, stats);
  const plans = planOperations(api, entityNames, stats);

  if (plans.length === 0) {
    throw new OpenApiAdaptError(
      `${specPath} declares no operations`,
      ["The spec parsed cleanly but its `paths` object contains no GET/POST/PUT/PATCH/DELETE operations, so there is nothing to import."]
    );
  }

  return {
    files: {
      "app.flow": buildAppFlow(api, notes),
      "schema.flow": schemaFlow,
      "actions.flow": buildActionsFlow(plans),
      "auth.flow": buildAuthFlow(plans),
    },
    stats,
    notes,
  };
}

// No workflows.flow is generated.
//
// An OpenAPI spec describes endpoints one at a time and says nothing about which of them
// belong together, so composing them is a decision only a human can make. A
// comments-only placeholder was tried and rejected: the compiler treats a file with no
// declarations as "Empty file" and fails the build, so the choice is between inventing a
// workflow nobody asked for and shipping none. Shipping none is right.
//
// The cost is one `AXL403 Optional file not found: workflows.flow` warning on a freshly
// imported project, which is accurate — there are no workflows yet.

/**
 * Re-attaches component names to dereferenced schema objects.
 *
 * `dereference` replaces every `$ref` with the object it pointed at, which is what we
 * want for reading properties -- but it also destroys the only clue that a property was
 * a reference to a named component rather than an inline object. Without this, every
 * `$ref: '#/components/schemas/Order'` would map to String with a "free-form object"
 * TODO instead of to the `Order` entity.
 */
function tagRefNames(api: any): any {
  const schemas = api?.components?.schemas;
  if (!schemas) return api;

  // Identity map from the resolved object back to its component name. Dereferencing
  // shares the same object instance across every use site, so this works by reference.
  const byObject = new Map<any, string>();
  for (const [name, schema] of Object.entries<any>(schemas)) {
    if (schema && typeof schema === "object") byObject.set(schema, name);
  }

  const seen = new Set<any>();
  const walk = (node: any): void => {
    if (!node || typeof node !== "object" || seen.has(node)) return;
    seen.add(node);

    const name = byObject.get(node);
    if (name && !node.$ref) {
      Object.defineProperty(node, "x-axl-ref-name", {
        value: `#/components/schemas/${name}`,
        enumerable: false,
        configurable: true,
      });
    }

    for (const value of Object.values(node)) {
      if (Array.isArray(value)) value.forEach(walk);
      else walk(value);
    }
  };
  walk(api);

  return api;
}
